## what is Numpy

Numpy (Numerical Python) is an open source Python library that is used for arrays manipulations. It can be used to store data in one, two, three, ..., n dimensional arrays

## Difference between numpy and python list:

* numpy arrays store only data with same type however list can store different types of data

* lists consumes more memory for storage than numpy which lead it to be slower.
* Numpy uses contiguous memory and lists does not


##Install Numpy

In [ ]:
#!pip install numpy

## Import Numpy

In [ ]:
import numpy as np
import numpy as np



[ 3 12]


## create arrays with numpy

In [ ]:
#create 1D numpy array
a1 = np.array([1.0, 2,3], dtype="float16")
a1

array([1., 2., 3.], dtype=float16)

In [ ]:
#create 2D numpy arrays
a2 =np.array([[1,2,3], [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# create 3D array
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## Dimension, shapes and types

In [ ]:
#Dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
#shape
a1.shape
a2.shape
a3.shape

(1, 3, 3)

In [ ]:
#types
a1.dtype

dtype('float16')

## Accessing elements in numpy array (indexing and slicing)

---



In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [ ]:
%%timeit
#indexing
A[1][1]
A[1,1]

159 ns ± 50.6 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [ ]:
#slicing
A[0:2, 1:3]

array([[2, 3],
       [5, 6]])

##Exercise:

Write a code using slicing to reverse a numpy 1D array


In [ ]:
x = np.array([1,2,3])
## code here
x = x[::-1]
x

array([3, 2, 1])

# Boolean or “mask” index arrays
#### Boolean arrays used as indices are treated in a different manner entirely than index arrays. Boolean arrays must be of the same shape as the initial dimensions of the array being indexed. In the most straightforward case, the boolean array has the same shape:

In [ ]:
y = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])
y.shape

(5, 4)

In [ ]:
#check if all values in y are > 15 and < 20
x = (y > 15) & (y < 20)
x

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [ ]:
x.astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

## np.where()

In [ ]:
#replace all values in y that are > 15 by -1 using np.where
np.where((y>15), -1, y)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [-1, -1, -1, -1]])

## Exercise:

Replace all even numbers in the given array with -1 using np.where

In [ ]:
#write answer here
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(x % 2 == 0, -1, x)


array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

## Initializing arrays

In [ ]:
#create matrix with only ones
np.ones((3,3), dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
## create a matrix with only zeros
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Ex:

Write a code to create a numpy zero vector of size 10 and update element at index 5 and 6 with values to 10 and 11



In [ ]:
## code here

##Ex:

Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [ ]:
## code here
A=np.ones((4,7))
A[1:-1,1:-1]=0
A

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
## matrix with any other value np.full
np.full((3,3), 5)


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# create matrix with random values sampled from a uniform distribution(np.random.rand)
np.random.rand(2,3)

array([[0.95224063, 0.02266368, 0.26380891],
       [0.61556929, 0.07773875, 0.90313725]])

In [ ]:
# create matrix with random values sampled from a normal distribution(np.random.randn)
np.random.randn(2,3)

array([[ 1.1326953 , -0.8793458 , -0.27364758],
       [ 1.87604583, -0.88336921,  0.90396947]])

In [ ]:
# create matrix with random int values from 0 to 10(np.random.randint)
np.random.randint(0, 10, (3,3))

array([[3, 5, 3],
       [0, 5, 6],
       [0, 5, 1]])

In [ ]:
## create identity matrix(np.identity)
np.identity(2)


array([[1., 0.],
       [0., 1.]])

In [ ]:
## create matrix containing numbers from 0 to 10(np.arange)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## create matrix containing even numbers from 0 to 10(np.arange)
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### *When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:*

In [ ]:
#create an array of 8 elements between 0 and 3(np.linspace)
x = np.linspace(0, 3, 8)
x.shape

(8,)

In [ ]:
x = x.reshape(2,4)
x.shape

(2, 4)

In [ ]:
x

array([[0.        , 0.42857143, 0.85714286, 1.28571429],
       [1.71428571, 2.14285714, 2.57142857, 3.        ]])

#Ex:

Write a code to create a numpy 3x3 matrix with values ranging from 2 to 10. 

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## Copying matrix

In [ ]:
a = np.array([1,2,3,4])

#copy a in b
a

array([1, 2, 3, 4])

In [ ]:
b = a
b[0] = 10
b

array([10,  2,  3,  4])

In [ ]:
a

array([10,  2,  3,  4])

In [ ]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 10

In [ ]:
b

array([10,  2,  3,  4])

In [ ]:
a

array([1, 2, 3, 4])

## Math and numpy

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum
# print(x + y)
# print(np.add(x, y))




# Elementwise difference
# print(x - y)
# print(np.subtract(x,y))

# Elementwise product
# print(x * y)
# print(np.multiply(x, y))

# Elementwise division
print(np.divide(x,y))
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


\* is elementwise multiplication, not matrix multiplication. .dot function is used to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

## vector product, v and w
print(np.dot(v, w))



# Matrix / vector product, x and v
print(np.dot(x, v))

# Matrix / matrix product, x and y
print(np.dot(x,y))

219
[29 67]
[[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2, 3],[3,4, 5]])
print(np.sum(x))



 # Compute sum of all elements
  # Compute sum of each column
print(np.sum(x, axis=0))
# Compute sum of each row
print(np.sum(x, axis=1))

18
[4 6 8]
[ 6 12]


In [ ]:
x = np.array([[1,2],[3,4]])
np.mean(x)
# Compute the mean of all elements
  # Compute mean of each column
 # Compute mean of each row

In [ ]:
x = np.array([[1,2],[3,4]])
np.std(x)
# Compute std of all elements
# Compute std of each column
# Compute std of each row

In [ ]:
x = np.array([1,2,3,4]) # each value is considered as an angle
#cos and sin of x

## Exercises:

Calculate the sum of the diagonal elements of a NumPy array using np.trace() and np.diagonal

In [ ]:

x = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.sum(np.diagonal(x))

15

In [ ]:
## write answer here

## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

Two arrays can be broadcasted if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])
print(x.shape)
print(v.shape)
y = x + v  # Add v to each row of x using broadcasting
print(y)
print("=="*10)
w = np.array([[1], [0], [1]])
print(w.shape)
print(x+w)

(3, 3)
(3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
(3, 1)
[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]]


In [ ]:
v = np.array([1,2,3]) 
w = np.array([4,5])   
print(v.shape)
print(w.shape) 
#we need to reshape v to be a column vector of shape (3, 1); we can then broadcast it against w 
y = v.reshape(3,1) * w
print(y)
print(y.shape)


(3,)
(2,)
[[ 4  5]
 [ 8 10]
 [12 15]]
(3, 2)


## Numpy and linear algebra

In [ ]:
x = np.random.randint(0, 20, 10).reshape(5,2)
x

array([[13,  5],
       [ 2,  0],
       [ 0, 18],
       [ 1,  2],
       [ 3,  7]])

### Norm:

In [ ]:
#compute norm of x
np.linalg.norm(x)

In [ ]:
#compute norm 1 of x
np.linalg.norm(x, ord="fro")

24.186773244895647

In [ ]:
#compute norm 2 of x
np.linalg.norm(x, ord=np.inf)

18.0

### Eigen values and vectors

In [ ]:

x = np.random.randint(0, 20, (3,3))
#compute the eigen values of x
np.linalg.eig(x)

(array([41.89339225, -3.48428523,  8.59089298]),
 array([[-0.63852831, -0.77030436, -0.1529931 ],
        [-0.69187553,  0.41340283, -0.57219614],
        [-0.33703091,  0.48551962,  0.80571998]]))

### determinant

In [ ]:
#compute determinant of x
np.linalg.det(x)

-1254.0000000000005

### Inverse matrix

In [ ]:
#compute the inverse matrix of x
np.linalg.inv(x)

array([[-0.17065391,  0.15311005,  0.05422648],
       [ 0.09170654, -0.0215311 , -0.08054226],
       [ 0.13636364, -0.13636364,  0.04545455]])

## More in Numpy

https://numpy.org/doc/stable/user/absolute_beginners.html

https://realpython.com/numpy-tutorial  